namespace Cake.Issues.JUnit;

using Cake.Core;
using Cake.Core.Annotations;
using Cake.Issues.JUnit.LogFileFormat;

/// <content>
/// Aliases for provider to read issues in JUnit file format generated by CppLint.
/// </content>
public static partial class JUnitIssuesAliases
{
    /// <summary>
    /// Gets an instance for the log format for cpplint JUnit XML output.
    /// Optimized for cpplint's specific JUnit format where test case names represent file names.
    /// </summary>
    /// <param name="context">The context.</param>
    /// <returns>Instance for the cpplint JUnit XML format.</returns>
    [CakePropertyAlias]
    [CakeAliasCategory(IssuesAliasConstants.IssueProviderCakeAliasCategory)]
    public static BaseJUnitLogFileFormat CppLintJUnitLogFileFormat(
        this ICakeContext context)
    {
        context.NotNull();

        return new CppLintLogFileFormat(context.Log);
    }
}