namespace Cake.Issues.JUnit;

using Cake.Core;
using Cake.Core.Annotations;
using Cake.Issues.JUnit.LogFileFormat;

/// <content>
/// Aliases for provider to read issues in JUnit file format generated by markdownlint-cli2.
/// </content>
public static partial class JUnitIssuesAliases
{
    /// <summary>
    /// Gets an instance for the log format for markdownlint-cli2 JUnit XML output.
    /// Optimized for markdownlint-cli2's specific JUnit format where file paths are in classname attributes.
    /// </summary>
    /// <param name="context">The context.</param>
    /// <returns>Instance for the markdownlint-cli2 JUnit XML format.</returns>
    [CakePropertyAlias]
    [CakeAliasCategory(IssuesAliasConstants.IssueProviderCakeAliasCategory)]
    public static BaseJUnitLogFileFormat MarkdownlintCli2JUnitLogFileFormat(
        this ICakeContext context)
    {
        context.NotNull();

        return new MarkdownlintCli2LogFileFormat(context.Log);
    }
}