environment:
  # Disable publishing to GitHub package repository, since it will fail for
  # Cake.Issues.Reporting and Cake.Issues.PullRequests because an archived repo with that name exists.
  GPR_SOURCE:

#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2022

init:
  - git config --global core.autocrlf true

#---------------------------------#
#  Install .NET                   #
#---------------------------------#
install:
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: Invoke-WebRequest -Uri "https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1" -OutFile "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1"
  # .NET 5 required for Codecov.Tool
  - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Version 5.0.408 -InstallDir $env:DOTNET_INSTALL_DIR'
  - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Version 8.0.411 -InstallDir $env:DOTNET_INSTALL_DIR'
  - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Version 9.0.301 -InstallDir $env:DOTNET_INSTALL_DIR'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
  - ps: dotnet --info

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 --target=CI

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- tools -> recipe.cake
