environment:
  # Disable publishing to GitHub package repository, since it will fail for
  # Cake.Issues.Reporting and Cake.Issues.PullRequests because an archived repo with that name exists.
  GPR_SOURCE:

#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2022

#---------------------------------#
#  Build Script                   #
#---------------------------------#
install:
  # Update to latest NuGet version since we require 5.3.0 for embedded icon
  - ps: nuget update -self

build_script:
  - ps: .\build.ps1 --target=CI

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- tools -> recipe.cake
