trigger:
- develop
- master
- release/*
- hotfix/*

pr:
- develop

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: |
      $ENV:CAKE_SKIP_GITVERSION=([string]::IsNullOrEmpty($ENV:SYSTEM_PULLREQUEST_PULLREQUESTID) -eq $False).ToString()
      .\build.ps1
      exit $LASTEXITCODE 
    displayName: 'Cake Build'
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - bash: |
      ./build.sh
    displayName: 'Cake Build'