trigger:
  branches:
    include:
      - develop
      - master
      - release/*
      - hotfix/*
  paths:
    exclude:
      - docs/**

pr:
  branches:
    include:
      - develop
      - release/*
      - hotfix/*
  paths:
    exclude:
      - docs/**

stages:
  - template: .azuredevops/pipelines/templates/stages/build.yml
  - template: .azuredevops/pipelines/templates/stages/unit-tests.yml
  - template: .azuredevops/pipelines/templates/stages/build-for-integration-tests.yml
  - template: .azuredevops/pipelines/templates/stages/integration-tests-git-repository.yml
  - template: .azuredevops/pipelines/templates/stages/integration-tests-markdownlint.yml
  - template: .azuredevops/pipelines/templates/stages/integration-tests-msbuild.yml
  - template: .azuredevops/pipelines/templates/stages/integration-tests-reporting-console.yml
  - template: .azuredevops/pipelines/templates/stages/integration-tests-reporting-generic.yml
  - template: .azuredevops/pipelines/templates/stages/integration-tests-reporting-sarif.yml