trigger:
- develop
- master
- release/*
- hotfix/*

pr:
- develop
- release/*
- hotfix/*

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2022'
  steps:
  # .NET 5 required for GitVersion
  - task: UseDotNet@2
    inputs:
      version: '5.x'
  - task: UseDotNet@2
    inputs:
      version: '6.x'
  - task: UseDotNet@2
    inputs:
      version: '7.x'
  - task: UseDotNet@2
    inputs:
      version: '8.x'
  - powershell: ./build.ps1
    displayName: 'Cake Build'
- job: Linux
  pool:
    vmImage: 'ubuntu-22.04'
  steps:
  # .NET 5 required for GitVersion
  - task: UseDotNet@2
    inputs:
      version: '5.x'
  - task: UseDotNet@2
    inputs:
      version: '6.x'
  - task: UseDotNet@2
    inputs:
      version: '7.x'
  - task: UseDotNet@2
    inputs:
      version: '8.x'
  - bash: ./build.sh
    displayName: 'Cake Build'
- job: macOS
  pool:
    vmImage: 'macOS-12'
  steps:
  # .NET 5 required for GitVersion
  - task: UseDotNet@2
    inputs:
      version: '5.x'
  - task: UseDotNet@2
    inputs:
      version: '6.x'
  - task: UseDotNet@2
    inputs:
      version: '7.x'
  - task: UseDotNet@2
    inputs:
      version: '8.x'
  - bash: ./build.sh
    displayName: 'Cake Build'