trigger:
- develop
- master
- release/*
- hotfix/*

pr:
- develop
- release/*
- hotfix/*

stages:
- stage: BuildStage
  displayName: Full Build
  dependsOn: []
  jobs:
  - job: BuildJob
    displayName: Build
    pool:
      vmImage: 'windows-2022'
    steps:
    - template: .azuredevops/pipelines/templates/steps/install-required-dotnet-versions-for-building.yml 
    - bash: ./build.sh
      displayName: 'Build & Run Unit Tests'

- stage: UnitTestStage
  displayName: Unit Tests
  dependsOn: []
  jobs:
  - job: UnitTestJob
    displayName: Unit Tests
    strategy:
      matrix:
        Windows:
          imageName: 'windows-2022'
        Ubuntu:
          imageName: 'ubuntu-22.04'
        macOS:
          imageName: 'macOS-12'
    pool:
      vmImage: $(imageName)
    steps:
    - template: .azuredevops/pipelines/templates/steps/install-required-dotnet-versions-for-building.yml 
    - bash: ./build.sh --target=Test
      displayName: 'Run Unit Tests'

- stage: IntegrationTestsBuildStage
  displayName: Build
  dependsOn: []
  jobs:
  - job: CreateNuGetPackagesJob
    displayName: Create NuGet Packages
    pool:
      vmImage: 'ubuntu-22.04'
    steps:
    - template: .azuredevops/pipelines/templates/steps/install-required-dotnet-versions-for-building.yml 
    - bash: ./build.sh --target=Create-NuGet-Packages
      displayName: 'Build & Run Unit Tests'
    - publish: $(Build.SourcesDirectory)/BuildArtifacts/Packages/NuGet
      artifact: NuGet Package
      displayName: 'Publish NuGet package as build artifact'

- stage: IntegrationTestsGitRepositoryStage
  displayName: Integration Tests Cake.Issues.GitRepository
  dependsOn: IntegrationTestsBuildStage
  jobs:
  - job: TestGitRepositoryScriptingJob
    displayName: Test Cake Scripting
    strategy:
      matrix:
        Windows_Server_2019:
          imageName: 'windows-2019'
        Windows_Server_2022:
          imageName: 'windows-2022'
        macOS_11:
          imageName: 'macOS-11'
        macOS_13:
          imageName: 'macOS-13'
        Ubuntu_20_04:
          imageName: 'ubuntu-20.04'
        Ubuntu_22_04:
          imageName: 'ubuntu-22.04'
    pool:
      vmImage: $(imageName)
    steps:
    - template: .azuredevops/pipelines/templates/steps/install-net6.yml 
    - template: .azuredevops/pipelines/templates/steps/provide-nuget-packages.yml 
    - powershell: ./build.ps1 --verbosity=diagnostic
      workingDirectory: ./tests/Cake.Issues.GitRepository/script-runner
      displayName: 'Run integration tests'
    - publish: $(Build.SourcesDirectory)/BuildArtifacts/TestResults/Integration
      artifact: Integration Tests Cake.Issues.GitRepository Cake Scripting $(System.JobName)
      displayName: 'Publish generated reports as build artifact'

- stage: IntegrationTestsMarkdownlintStage
  displayName: Integration Tests Cake.Issues.Markdownlint
  dependsOn: IntegrationTestsBuildStage
  jobs:
  - job: TestMarkdownlintJob
    displayName: Test
    strategy:
      matrix:
        Windows_Server_2019:
          imageName: 'windows-2019'
        Windows_Server_2022:
          imageName: 'windows-2022'
        macOS_11:
          imageName: 'macOS-11'
        macOS_13:
          imageName: 'macOS-13'
        Ubuntu_20_04:
          imageName: 'ubuntu-20.04'
        Ubuntu_22_04:
          imageName: 'ubuntu-22.04'
    pool:
      vmImage: $(imageName)
    steps:
    - template: .azuredevops/pipelines/templates/steps/install-net6.yml 
    - template: .azuredevops/pipelines/templates/steps/install-markdownlint.yml 
    - template: .azuredevops/pipelines/templates/steps/provide-nuget-packages.yml 
    - powershell: ./build.ps1 --verbosity=diagnostic
      workingDirectory: ./tests/Cake.Issues.Markdownlint
      displayName: 'Run integration tests'
    - publish: $(Build.SourcesDirectory)/tests/Cake.Issues.Markdownlint/output/report.html
      artifact: Integration Tests Cake.Issues.Markdownlint $(System.JobName)
      displayName: 'Publish generated reports as build artifact'

- stage: IntegrationTestsMsBuildStage
  displayName: Integration Tests Cake.Issues.MsBuild
  dependsOn: IntegrationTestsBuildStage
  jobs:
  - job: TestMsBuildJob
    displayName: Test
    strategy:
      matrix:
        Windows_Server_2019:
          imageName: 'windows-2019'
        Windows_Server_2022:
          imageName: 'windows-2022'
        macOS_11:
          imageName: 'macOS-11'
        macOS_13:
          imageName: 'macOS-13'
        Ubuntu_20_04:
          imageName: 'ubuntu-20.04'
        Ubuntu_22_04:
          imageName: 'ubuntu-22.04'
    pool:
      vmImage: $(imageName)
    steps:
    - template: .azuredevops/pipelines/templates/steps/install-net6.yml 
    - template: .azuredevops/pipelines/templates/steps/provide-nuget-packages.yml 
    - powershell: ./build.ps1 --verbosity=diagnostic
      workingDirectory: ./tests/Cake.Issues.MsBuild/script-runner
      displayName: 'Run integration tests'

- stage: IntegrationTestsReportingConsoleStage
  displayName: Integration Tests Cake.Issues.Reporting.Console
  dependsOn: IntegrationTestsBuildStage
  jobs:
  - job: TestReportingConsoleScriptingJob
    displayName: Test Cake Scripting
    strategy:
      matrix:
        Windows_Server_2019:
          imageName: 'windows-2019'
        Windows_Server_2022:
          imageName: 'windows-2022'
        macOS_11:
          imageName: 'macOS-11'
        macOS_13:
          imageName: 'macOS-13'
        Ubuntu_20_04:
          imageName: 'ubuntu-20.04'
        Ubuntu_22_04:
          imageName: 'ubuntu-22.04'
    pool:
      vmImage: $(imageName)
    steps:
    - template: .azuredevops/pipelines/templates/steps/install-net6.yml 
    - template: .azuredevops/pipelines/templates/steps/provide-nuget-packages.yml 
    - powershell: ./build.ps1 --verbosity=diagnostic
      workingDirectory: ./tests/Cake.Issues.Reporting.Console/script-runner
      displayName: 'Run integration tests'
  - job: TestReportingConsoleFrostingNet6Job
    displayName: Test Cake Frosting .NET 6
    strategy:
      matrix:
        Windows_Server_2019:
          imageName: 'windows-2019'
        Windows_Server_2022:
          imageName: 'windows-2022'
        macOS_11:
          imageName: 'macOS-11'
        macOS_13:
          imageName: 'macOS-13'
        Ubuntu_20_04:
          imageName: 'ubuntu-20.04'
        Ubuntu_22_04:
          imageName: 'ubuntu-22.04'
    pool:
      vmImage: $(imageName)
    steps:
    - template: .azuredevops/pipelines/templates/steps/install-net6.yml 
    - template: .azuredevops/pipelines/templates/steps/provide-nuget-packages.yml 
    - powershell: ./build.ps1 --verbosity=diagnostic
      workingDirectory: ./tests/Cake.Issues.Reporting.Console/frosting/net6.0
      displayName: 'Run integration tests'

- stage: IntegrationTestsReportingGenericStage
  displayName: Integration Tests Cake.Issues.Reporting.Generic
  dependsOn: IntegrationTestsBuildStage
  jobs:
  - job: TestReportingGenericScriptingJob
    displayName: Test Cake Scripting
    strategy:
      matrix:
        Windows_Server_2019:
          imageName: 'windows-2019'
        Windows_Server_2022:
          imageName: 'windows-2022'
        macOS_11:
          imageName: 'macOS-11'
        macOS_13:
          imageName: 'macOS-13'
        Ubuntu_20_04:
          imageName: 'ubuntu-20.04'
        Ubuntu_22_04:
          imageName: 'ubuntu-22.04'
    pool:
      vmImage: $(imageName)
    steps:
    - template: .azuredevops/pipelines/templates/steps/install-net6.yml 
    - template: .azuredevops/pipelines/templates/steps/install-markdownlint.yml 
    - template: .azuredevops/pipelines/templates/steps/provide-nuget-packages.yml 
    - powershell: ./build.ps1 --verbosity=diagnostic
      workingDirectory: ./tests/Cake.Issues.Reporting.Generic/script-runner
      displayName: 'Run integration tests'
    - publish: $(Build.SourcesDirectory)/docs/input/docs/report-formats/generic/templates
      artifact: Integration Tests Cake.Issues.Reporting.Generic Cake Scripting $(System.JobName)
      displayName: 'Publish generated reports as build artifact'
  - job: TestReportingGenericFrostingNet6Job
    displayName: Test Cake Frosting .NET 6
    strategy:
      matrix:
        Windows_Server_2019:
          imageName: 'windows-2019'
        Windows_Server_2022:
          imageName: 'windows-2022'
        macOS_11:
          imageName: 'macOS-11'
        macOS_13:
          imageName: 'macOS-13'
        Ubuntu_20_04:
          imageName: 'ubuntu-20.04'
        Ubuntu_22_04:
          imageName: 'ubuntu-22.04'
    pool:
      vmImage: $(imageName)
    steps:
    - template: .azuredevops/pipelines/templates/steps/install-net6.yml 
    - template: .azuredevops/pipelines/templates/steps/install-markdownlint.yml 
    - template: .azuredevops/pipelines/templates/steps/provide-nuget-packages.yml 
    - powershell: ./build.ps1 --verbosity=diagnostic
      workingDirectory: ./tests/Cake.Issues.Reporting.Generic/frosting
      displayName: 'Run integration tests'
    - publish: $(Build.SourcesDirectory)/docs/input/docs/report-formats/generic/templates
      artifact: Integration Tests Cake.Issues.Reporting.Generic Cake Frosting .NET 6 $(System.JobName)
      displayName: 'Publish generated reports as build artifact'

- stage: IntegrationTestsReportingSarifStage
  displayName: Integration Tests Cake.Issues.Reporting.Sarif
  dependsOn: IntegrationTestsBuildStage
  jobs:
  - job: TestReportingSarifScriptingJob
    displayName: Test Cake Scripting
    strategy:
      matrix:
        Windows_Server_2019:
          imageName: 'windows-2019'
        Windows_Server_2022:
          imageName: 'windows-2022'
        macOS_11:
          imageName: 'macOS-11'
        macOS_13:
          imageName: 'macOS-13'
        Ubuntu_20_04:
          imageName: 'ubuntu-20.04'
        Ubuntu_22_04:
          imageName: 'ubuntu-22.04'
    pool:
      vmImage: $(imageName)
    steps:
    - template: .azuredevops/pipelines/templates/steps/install-net6.yml 
    - template: .azuredevops/pipelines/templates/steps/install-markdownlint.yml 
    - template: .azuredevops/pipelines/templates/steps/provide-nuget-packages.yml 
    - powershell: ./build.ps1 --verbosity=diagnostic
      workingDirectory: ./tests/Cake.Issues.Reporting.Sarif/script-runner
      displayName: 'Run integration tests'
    - publish: $(Build.SourcesDirectory)/tests/Cake.Issues.Reporting.Sarif/script-runner/output
      artifact: Integration Tests Cake.Issues.Reporting.Sarif Cake Scripting $(System.JobName)
      displayName: 'Publish generated reports as build artifact'
  - job: TestReportingSarifFrostingNet6Job
    displayName: Test Cake Frosting .NET 6
    strategy:
      matrix:
        Windows_Server_2019:
          imageName: 'windows-2019'
        Windows_Server_2022:
          imageName: 'windows-2022'
        macOS_11:
          imageName: 'macOS-11'
        macOS_13:
          imageName: 'macOS-13'
        Ubuntu_20_04:
          imageName: 'ubuntu-20.04'
        Ubuntu_22_04:
          imageName: 'ubuntu-22.04'
    pool:
      vmImage: $(imageName)
    steps:
    - template: .azuredevops/pipelines/templates/steps/install-net6.yml 
    - template: .azuredevops/pipelines/templates/steps/install-markdownlint.yml 
    - template: .azuredevops/pipelines/templates/steps/provide-nuget-packages.yml 
    - powershell: ./build.ps1 --verbosity=diagnostic
      workingDirectory: ./tests/Cake.Issues.Reporting.Sarif/frosting/net6
      displayName: 'Run integration tests'
    - publish: $(Build.SourcesDirectory)/tests/Cake.Issues.Reporting.Sarif/frosting/output
      artifact: Integration Tests Cake.Issues.Reporting.Sarif Cake Frosting .NET 6 $(System.JobName)
      displayName: 'Publish generated reports as build artifact'
  - job: TestReportingSarifFrostingNet7Job
    displayName: Test Cake Frosting .NET 7
    strategy:
      matrix:
        Windows_Server_2019:
          imageName: 'windows-2019'
        Windows_Server_2022:
          imageName: 'windows-2022'
        macOS_11:
          imageName: 'macOS-11'
        macOS_13:
          imageName: 'macOS-13'
        Ubuntu_20_04:
          imageName: 'ubuntu-20.04'
        Ubuntu_22_04:
          imageName: 'ubuntu-22.04'
    pool:
      vmImage: $(imageName)
    steps:
    - template: .azuredevops/pipelines/templates/steps/install-net7.yml 
    - template: .azuredevops/pipelines/templates/steps/install-markdownlint.yml 
    - template: .azuredevops/pipelines/templates/steps/provide-nuget-packages.yml 
    - powershell: ./build.ps1 --verbosity=diagnostic
      workingDirectory: ./tests/Cake.Issues.Reporting.Sarif/frosting/net7
      displayName: 'Run integration tests'
    - publish: $(Build.SourcesDirectory)/tests/Cake.Issues.Reporting.Sarif/frosting/output
      artifact: Integration Tests Cake.Issues.Reporting.Sarif Cake Frosting .NET 7 $(System.JobName)
      displayName: 'Publish generated reports as build artifact'
  - job: TestReportingSarifFrostingNet8Job
    displayName: Test Cake Frosting .NET 8
    strategy:
      matrix:
        Windows_Server_2019:
          imageName: 'windows-2019'
        Windows_Server_2022:
          imageName: 'windows-2022'
        macOS_11:
          imageName: 'macOS-11'
        macOS_13:
          imageName: 'macOS-13'
        Ubuntu_20_04:
          imageName: 'ubuntu-20.04'
        Ubuntu_22_04:
          imageName: 'ubuntu-22.04'
    pool:
      vmImage: $(imageName)
    steps:
    - template: .azuredevops/pipelines/templates/steps/install-net8.yml 
    - template: .azuredevops/pipelines/templates/steps/install-markdownlint.yml 
    - template: .azuredevops/pipelines/templates/steps/provide-nuget-packages.yml 
    - powershell: ./build.ps1 --verbosity=diagnostic
      workingDirectory: ./tests/Cake.Issues.Reporting.Sarif/frosting/net8
      displayName: 'Run integration tests'
    - publish: $(Build.SourcesDirectory)/tests/Cake.Issues.Reporting.Sarif/frosting/output
      artifact: Integration Tests Cake.Issues.Reporting.Sarif Cake Frosting .NET 8 $(System.JobName)
      displayName: 'Publish generated reports as build artifact'
