trigger:
- develop
- master
- release/*
- hotfix/*

pr:
- develop
- release/*
- hotfix/*

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2022'
  steps:
  - template: .azuredevops/pipelines/templates/steps/install-required-dotnet-versions-for-building.yml 
  - powershell: ./build.ps1
    displayName: 'Cake Build'
- job: Linux
  pool:
    vmImage: 'ubuntu-22.04'
  steps:
  - template: .azuredevops/pipelines/templates/steps/install-required-dotnet-versions-for-building.yml 
  - bash: ./build.sh
    displayName: 'Cake Build'
- job: macOS
  pool:
    vmImage: 'macOS-12'
  steps:
  - template: .azuredevops/pipelines/templates/steps/install-required-dotnet-versions-for-building.yml 
  - bash: ./build.sh
    displayName: 'Cake Build'