trigger:
- develop
- master
- release/*
- hotfix/*

pr:
- develop
- release/*
- hotfix/*

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build & Unit Tests
    strategy:
      matrix:
        Windows:
          imageName: 'windows-2022'
        Ubuntu:
          imageName: 'ubuntu-22.04'
        macOS:
          imageName: 'macOS-12'
    pool:
      vmImage: $(imageName)
    steps:
    - template: .azuredevops/pipelines/templates/steps/install-required-dotnet-versions-for-building.yml 
    - bash: ./build.sh
      displayName: 'Build & Run Unit Tests'
