name: 'InstallMarkdownlintAction'
description: 'Install Markdownlint'
runs:
  using: "composite"
  steps:
    - name: Install NodeJs
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: '22'
    - name: Install markdownlint
      run: |
        npm install -g markdownlint-cli
      shell: bash
