name: 'InstallMarkdownlintAction'
description: 'Install Markdownlint'
runs:
  using: "composite"
  steps:
    - name: Install NodeJs
      uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
      with:
        node-version: '24'
    - name: Install markdownlint
      run: |
        npm install -g markdownlint-cli@0.49.1
      shell: bash
