name: 'InstallMarkdownlintAction'
description: 'Install Markdownlint'
runs:
  using: "composite"
  steps:
    - name: Install NodeJs
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: '24'
    - name: Install markdownlint
      run: |
        npm install -g markdownlint-cli@0.46.0
      shell: bash
