name: 'InstallMarkdownlintAction'
description: 'Install Markdownlint'
runs:
  using: "composite"
  steps:
    - name: Install NodeJs
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: '24'
    - name: Install markdownlint
      run: |
        npm install -g markdownlint-cli
      shell: bash
