FROM mcr.microsoft.com/dotnet/sdk:8.0.413-bookworm-slim@sha256:c0e30f202cfe2461b2755235f15fbe782e82e56da9f43fc5e2c5eed9e1c6297d

RUN wget https://aka.ms/getvsdbgsh && \
    sh getvsdbgsh -v latest  -l /vsdbg