# Runs integration tests for Cake.Issues.Markdownlint on different platforms

stages:
  - stage: IntegrationTestsMarkdownlintStage
    displayName: Integration Tests Cake.Issues.Markdownlint
    dependsOn: IntegrationTestsBuildStage
    jobs:
    - job: TestMarkdownlintJob
      displayName: Test
      strategy:
        matrix:
          Windows_Server_2022:
            imageName: 'windows-2022'
          Windows_Server_2025:
            imageName: 'windows-2025'
          macOS_13:
            imageName: 'macOS-13'
          macOS_14:
            imageName: 'macOS-14'
          Ubuntu_22_04:
            imageName: 'ubuntu-22.04'
          Ubuntu_24_04:
            imageName: 'ubuntu-24.04'
      pool:
        vmImage: $(imageName)
      steps:
      - template: ../steps/install-net8.yml 
      - template: ../steps/install-markdownlint.yml 
      - template: ../steps/provide-nuget-packages.yml 
      - powershell: ./build.ps1 --verbosity=diagnostic
        workingDirectory: ./tests/Cake.Issues.Markdownlint/script-runner/net8.0
        displayName: 'Run integration tests'
      - publish: $(Build.SourcesDirectory)/tests/Cake.Issues.Markdownlint/script-runner/net8.0/output/report.html
        artifact: Integration Tests Cake.Issues.Markdownlint $(System.JobName)
        displayName: 'Publish generated reports as build artifact'