# Runs integration tests for Cake.Issues.GitRepository on different platforms

stages:
  - stage: IntegrationTestsGitRepositoryStage
    displayName: Integration Tests Cake.Issues.GitRepository
    dependsOn: IntegrationTestsBuildStage
    jobs:
    - job: TestGitRepositoryScriptingJob
      displayName: Test Cake Scripting
      strategy:
        matrix:
          Windows_Server_2022:
            imageName: 'windows-2022'
          Windows_Server_2025:
            imageName: 'windows-2025'
          macOS_13:
            imageName: 'macOS-13'
          macOS_14:
            imageName: 'macOS-14'
          Ubuntu_22_04:
            imageName: 'ubuntu-22.04'
          Ubuntu_24_04:
            imageName: 'ubuntu-24.04'
      pool:
        vmImage: $(imageName)
      steps:
      - template: ../steps/install-net8.yml 
      - template: ../steps/provide-nuget-packages.yml 
      - powershell: ./build.ps1 --verbosity=diagnostic
        workingDirectory: ./tests/Cake.Issues.GitRepository/script-runner
        displayName: 'Run integration tests'
      - publish: $(Build.SourcesDirectory)/BuildArtifacts/TestResults/Integration
        artifact: Integration Tests Cake.Issues.GitRepository Cake Scripting $(System.JobName)
        displayName: 'Publish generated reports as build artifact'
