# Runs integration tests for Cake.Issues.Reporting.Generic on different platforms

stages:
  - stage: IntegrationTestsReportingGenericStage
    displayName: Integration Tests Cake.Issues.Reporting.Generic
    dependsOn: IntegrationTestsBuildStage
    jobs:
    - job: TestReportingGenericScriptingJob
      displayName: Test Cake Scripting
      strategy:
        matrix:
          Windows_Server_2019:
            imageName: 'windows-2019'
          Windows_Server_2022:
            imageName: 'windows-2022'
          macOS_13:
            imageName: 'macOS-13'
          macOS_14:
            imageName: 'macOS-14'
          Ubuntu_20_04:
            imageName: 'ubuntu-20.04'
          Ubuntu_22_04:
            imageName: 'ubuntu-22.04'
      pool:
        vmImage: $(imageName)
      steps:
      - template: ../steps/install-net6.yml 
      - template: ../steps/provide-nuget-packages.yml 
      - powershell: ./build.ps1 --verbosity=diagnostic
        workingDirectory: ./tests/Cake.Issues.Reporting.Generic/script-runner
        displayName: 'Run integration tests'
      - publish: $(Build.SourcesDirectory)/docs/input/docs/report-formats/generic/templates
        artifact: Integration Tests Cake.Issues.Reporting.Generic Cake Scripting $(System.JobName)
        displayName: 'Publish generated reports as build artifact'
    - job: TestReportingGenericFrostingNet6Job
      displayName: Test Cake Frosting .NET 6
      strategy:
        matrix:
          Windows_Server_2019:
            imageName: 'windows-2019'
          Windows_Server_2022:
            imageName: 'windows-2022'
          macOS_13:
            imageName: 'macOS-13'
          macOS_14:
            imageName: 'macOS-14'
          Ubuntu_20_04:
            imageName: 'ubuntu-20.04'
          Ubuntu_22_04:
            imageName: 'ubuntu-22.04'
      pool:
        vmImage: $(imageName)
      steps:
      - template: ../steps/install-net6.yml 
      - template: ../steps/provide-nuget-packages.yml 
      - powershell: ./build.ps1 --verbosity=diagnostic
        workingDirectory: ./tests/Cake.Issues.Reporting.Generic/frosting
        displayName: 'Run integration tests'
      - publish: $(Build.SourcesDirectory)/docs/input/docs/report-formats/generic/templates
        artifact: Integration Tests Cake.Issues.Reporting.Generic Cake Frosting .NET 6 $(System.JobName)
        displayName: 'Publish generated reports as build artifact'
