# Runs integration tests for Cake.Issues.Reporting.Console on different platforms

stages:
  - stage: IntegrationTestsReportingConsoleStage
    displayName: Integration Tests Cake.Issues.Reporting.Console
    dependsOn: IntegrationTestsBuildStage
    jobs:
    - job: TestReportingConsoleScriptingJob
      displayName: Test Cake Scripting
      strategy:
        matrix:
          Windows_Server_2019:
            imageName: 'windows-2019'
          Windows_Server_2022:
            imageName: 'windows-2022'
          macOS_13:
            imageName: 'macOS-13'
          macOS_14:
            imageName: 'macOS-14'
          Ubuntu_20_04:
            imageName: 'ubuntu-20.04'
          Ubuntu_22_04:
            imageName: 'ubuntu-22.04'
      pool:
        vmImage: $(imageName)
      steps:
      - template: ../steps/install-net6.yml 
      - template: ../steps/provide-nuget-packages.yml 
      - powershell: ./build.ps1 --verbosity=diagnostic
        workingDirectory: ./tests/Cake.Issues.Reporting.Console/script-runner
        displayName: 'Run integration tests'
    - job: TestReportingConsoleFrostingNet6Job
      displayName: Test Cake Frosting .NET 6
      strategy:
        matrix:
          Windows_Server_2019:
            imageName: 'windows-2019'
          Windows_Server_2022:
            imageName: 'windows-2022'
          macOS_13:
            imageName: 'macOS-13'
          macOS_14:
            imageName: 'macOS-14'
          Ubuntu_20_04:
            imageName: 'ubuntu-20.04'
          Ubuntu_22_04:
            imageName: 'ubuntu-22.04'
      pool:
        vmImage: $(imageName)
      steps:
      - template: ../steps/install-net6.yml 
      - template: ../steps/provide-nuget-packages.yml 
      - powershell: ./build.ps1 --verbosity=diagnostic
        workingDirectory: ./tests/Cake.Issues.Reporting.Console/frosting/net6.0
        displayName: 'Run integration tests'
