# Runs unit tests on different platforms

stages:
  - stage: UnitTestStage
    displayName: Unit Tests
    dependsOn: []
    jobs:
    - job: UnitTestJob
      displayName: Unit Tests
      strategy:
        matrix:
          Windows:
            imageName: 'windows-2022'
          Ubuntu:
            imageName: 'ubuntu-24.04'
          macOS:
            imageName: 'macOS-13'
      pool:
        vmImage: $(imageName)
      steps:
      - template: ../steps/install-required-dotnet-versions-for-building.yml 
      - task: UseDotNet@2
        inputs:
          version: '9.0.102'
        displayName: 'Install .NET 9'
      # Ubuntu 24.04 does not have Mono installed, which is Required for Cake.Recipe
      - bash: sudo apt-get install mono-complete
        condition: eq(variables['imageName'], 'ubuntu-24.04')
        displayName: 'Install Mono'
      - bash: ./build.sh --target=Test
        displayName: 'Run Unit Tests'