# Runs unit tests on different platforms

stages:
  - stage: UnitTestStage
    displayName: Unit Tests
    dependsOn: []
    jobs:
    - job: UnitTestJob
      displayName: Unit Tests
      strategy:
        matrix:
          Windows:
            imageName: 'windows-2022'
          Ubuntu:
            imageName: 'ubuntu-24.04'
          macOS:
            imageName: 'macOS-13'
      pool:
        vmImage: $(imageName)
      steps:
      - template: ../steps/install-required-dotnet-versions-for-building.yml 
      - bash: ./build.sh --target=Test
        displayName: 'Run Unit Tests'