name: 'PerpareIntegratoinTestAction'
description: 'Perpare for running integration test'
inputs:
  dotnet-version:
    description: '.NET SDK version(s) to use. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download build artifact
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        name: NuGet Package
        path: ./BuildArtifacts/Packages/NuGet
    - name: Install .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}