name: 'PerpareIntegratoinTestAction'
description: 'Perpare for running integration test'
inputs:
  dotnet-version:
    description: '.NET SDK version(s) to use. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download build artifact
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
      with:
        name: NuGet Package
        path: ./BuildArtifacts/Packages/NuGet
    - name: Install .NET
      uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}