name: 'PerpareIntegratoinTestAction'
description: 'Perpare for running integration test'
inputs:
  dotnet-version:
    description: '.NET SDK version(s) to use. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download build artifact
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: NuGet Package
        path: ./BuildArtifacts/Packages/NuGet
    - name: Install .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: Determine TFM
      run: |
        DOTNET_VERSION="${{ inputs.dotnet-version }}"
        DOTNET_MAJOR_VERSION="${DOTNET_VERSION%%.*}"
        echo "TFM=net${DOTNET_MAJOR_VERSION}.0" >> $GITHUB_ENV
      shell: bash
