name: Build

# Workflow Trigger
on:
  # Trigger the workflow on pushes to the master or develop branch, ignoring changes to /docs
  push:
    branches: 
      - develop
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  Test:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Get the sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - name: Install .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          # .NET 5 required for GitVersion
          # .NET 7 required for Cake.Recipe
          dotnet-version: | 
            5.x
            7.x
            8.x
            9.x
            10.x
      # Ubuntu 24.04 does not have Mono installed, which is required for Cake.Recipe
      - name: Install Mono
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete
      - name: Build
        run: ./build.sh --target=CI --verbosity=diagnostic
        shell: bash
        env:
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
          AZURE_SOURCE: ${{ secrets.AZURE_SOURCE }}
          AZURE_USER: ${{ secrets.AZURE_USER }}
          CODECOV_REPO_TOKEN: ${{ secrets.CODECOV_REPO_TOKEN }}
          GITHUB_PAT: ${{ secrets.GH_TOKEN }}
          GPR_SOURCE: ${{ secrets.GPR_SOURCE }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_SOURCE: "https://api.nuget.org/v3/index.json"
      - name: Upload Issues
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          if-no-files-found: warn
          name: Issues
          path: |
            BuildArtifacts/report.html
            BuildArtifacts/**/coverlet/*.xml
      - name: Upload Packages
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          if-no-files-found: warn
          name: package
          path: BuildArtifacts/Packages/**/*