name: Build NuGet packages

on:
  workflow_call:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-26.04
    steps:
      - name: Get the sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Create local branch for GitVersion
        if: github.event_name == 'pull_request'
        run: git checkout -b ${{ github.head_ref }}
      - name: Install .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          # .NET 5 required for GitVersion
          # .NET 7 required for Cake.Recipe
          dotnet-version: |
            5.x
            7.x
            8.x
            9.x
            10.x
      # Ubuntu 26.04 does not have Mono installed, which is required for Cake.Recipe
      - name: Install Mono
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete
      - name: Build
        run: ./build.sh --target=Create-NuGet-Packages
        shell: bash
      - name: Publish NuGet package as build artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: NuGet Package
          path: ./BuildArtifacts/Packages/NuGet/
