name: Integration tests

# Workflow Trigger
on:
  # Trigger the workflow on a pull request to any branch
  pull_request:
  # Triggers the workflow in the event there is a push to master
  push:
    branches: 
      - master

jobs:
  # Build
  Build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Get the sources
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - name: Install .NET
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4
        with:
          # .NET 5 required for GitVersion
          dotnet-version: | 
            5.x
            6.x
            7.x
            8.x
      - name: Build
        run: ./build.sh --target=Create-NuGet-Packages
        shell: bash
      - name: Publish NuGet package as build artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: NuGet Package
          path: ./BuildArtifacts/Packages/NuGet/
  # Integration Tests Cake.Issues.GitRepository Cake Scripting
  IntegrationTestsGitRepositoryCakeScripting:
    name: Integration Tests Cake.Issues.GitRepository Cake Scripting
    needs: Build
    strategy:
      fail-fast: false
      matrix:
        os: [
          windows-2019, windows-2022,
          ubuntu-20.04, ubuntu-22.04,
          macos-12, macos-14]
        dotnet: [6.x, 7.x, 8.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the sources
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          lfs: true
      - name: Download build artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: NuGet Package
          path: ./BuildArtifacts/Packages/NuGet
      - name: Install .NET
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Run integration tests
        run: ./build.sh --verbosity=diagnostic
        working-directory: ./tests/Cake.Issues.GitRepository/script-runner/
        shell: bash
  # Integration Tests Cake.Issues.GitRepository Cake Scripting with sparse checkout
  IntegrationTestsGitRepositoryCakeScriptingSparseCheckout:
    name: Integration Tests Cake.Issues.GitRepository Cake Scripting with sparse checkout
    needs: Build
    strategy:
      fail-fast: false
      matrix:
        os: [
          windows-2019, windows-2022,
          ubuntu-20.04, ubuntu-22.04,
          macos-12, macos-14]
        dotnet: [6.x, 7.x, 8.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the sources
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          lfs: true
          sparse-checkout: |
            tests/Cake.Issues.GitRepository/script-runner/
      - name: Download build artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: NuGet Package
          path: ./BuildArtifacts/Packages/NuGet
      - name: Install .NET
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Run integration tests
        run: ./build.sh --verbosity=diagnostic
        working-directory: ./tests/Cake.Issues.GitRepository/script-runner/
        shell: bash
  # Integration Tests Cake.Issues.MsBuild Cake Scripting
  IntegrationTestsMsBuildCakeScripting:
    name: Integration Tests Cake.Issues.MsBuild Cake Scripting
    needs: Build
    strategy:
      fail-fast: false
      matrix:
        os: [
          windows-2019, windows-2022,
          ubuntu-20.04, ubuntu-22.04,
          macos-13, macos-14]
        dotnet: [6.x, 7.x, 8.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the sources
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Prepare integration tests
        uses: ./.github/actions/prepare-integration-test
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Run integration tests
        run: ./build.sh --verbosity=diagnostic
        working-directory: ./tests/Cake.Issues.MsBuild/script-runner/
        shell: bash
  # Integration Tests Cake.Issues.PullRequests.GitHubActions Cake Scripting
  IntegrationTestsPullRequestsGitHubActionsCakeScripting:
    name: Integration Tests Cake.Issues.PullRequests.GitHubActions Cake Scripting
    needs: Build
    strategy:
      fail-fast: false
      matrix:
        os: [
          windows-2019, windows-2022,
          ubuntu-20.04, ubuntu-22.04,
          macos-13, macos-14]
        dotnet: [6.x, 7.x, 8.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the sources
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Prepare integration tests
        uses: ./.github/actions/prepare-integration-test
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Run integration tests
        run: ./build.sh --verbosity=diagnostic
        working-directory: ./tests/Cake.Issues.PullRequests.GitHubActions/script-runner/
        shell: bash
