name: Integration tests

# Workflow Trigger
on:
  # Trigger the workflow on a pull request to any branch, ignoring changes to /docs
  pull_request:
    paths-ignore:
      - 'docs/**'
  # Trigger the workflow on pushes to the master branch, ignoring changes to /docs
  push:
    branches: 
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  # Build
  Build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Get the sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - name: Install .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          # .NET 5 required for GitVersion
          dotnet-version: | 
            5.x
            8.x
            9.x
      - name: Build
        run: ./build.sh --target=Create-NuGet-Packages
        shell: bash
      - name: Publish NuGet package as build artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: NuGet Package
          path: ./BuildArtifacts/Packages/NuGet/
  # Integration Tests Cake.Issues.MsBuild Cake Scripting
  IntegrationTestsMsBuildCakeScripting:
    name: Integration Tests Cake.Issues.MsBuild Cake Scripting
    needs: Build
    strategy:
      fail-fast: false
      matrix:
        os: [
          windows-2022, windows-2025, 
          ubuntu-22.04, ubuntu-24.04,
          macos-13, macos-14]
        dotnet: [8.x, 9.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Prepare integration tests
        uses: ./.github/actions/prepare-integration-test
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Determine TFM
        run: |
          DOTNET_VERSION="${{ matrix.dotnet }}"
          DOTNET_MAJOR_VERSION="${DOTNET_VERSION%%.*}"
          echo "TFM=net${DOTNET_MAJOR_VERSION}.0" >> $GITHUB_ENV
        shell: bash
      - name: Run integration tests
        run: ./build.sh --verbosity=diagnostic
        working-directory: ./tests/Cake.Issues.MsBuild/script-runner/${{ env.TFM }}
        shell: bash
  # Integration Tests Cake.Issues.PullRequests.GitHubActions Cake Scripting
  IntegrationTestsPullRequestsGitHubActionsCakeScripting:
    name: Integration Tests Cake.Issues.PullRequests.GitHubActions Cake Scripting
    needs: Build
    strategy:
      fail-fast: false
      matrix:
        os: [
          windows-2022, windows-2025,
          ubuntu-22.04, ubuntu-24.04,
          macos-13, macos-14]
        dotnet: [8.x, 9.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Prepare integration tests
        uses: ./.github/actions/prepare-integration-test
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Run integration tests
        run: ./build.sh --verbosity=diagnostic
        working-directory: ./tests/Cake.Issues.PullRequests.GitHubActions/script-runner/
        shell: bash
