name: Publish Develop Docs 

# Workflow Trigger
on:
  # Triggers the workflow in the event there is a push to develop
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  deploy:
    name: Build & Publish Docs
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: true
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.14.7
      - name: Install Python Dependencies
        run: pip install -r requirements.txt
        working-directory: ./docs
      - name: Install Required Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y pngquant
      - name: Configure Git
        run: |
          git config --global user.name "Build Server"
          git config --global user.email "ci@cakeissues.net"
      - name: Build & Publish
        run: mike deploy --push develop
        working-directory: ./docs
