name: PushPreview

# Workflow Trigger
on:
  # Triggers the workflow if a pull request is labeled with 'preview'
  pull_request_target:
    types:
      - labeled

jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'preview'
    steps:
      - name: Get the sources
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Comment
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body "⚙️ Hang tight! PushPreview is currently building your preview. We'll share the URL as soon as it's ready."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.13.6
      - name: Set BASE_URL
        run: echo "BASE_URL=/github/${{ github.repository }}/${{ github.event.number }}/" >> $GITHUB_ENV
      - name: Build site
        run: |
          cd docs
          pip install -r requirements.txt
          mkdocs build
      - name: Generate preview
        uses: PushLabsHQ/pushpreview-action@cf958f7be2bf55d3f56d351bb9abf56b4c6b9a50 # 1.0.6
        with:
          source-directory: ./docs/site
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pushpreview-token: ${{ secrets.PUSHPREVIEW_TOKEN }}