name: Renovate config validation

on:
  pull_request:
    paths:
      - .github/renovate.json

jobs:
  validate:
    name: Validate Renovate configuration
    runs-on: ubuntu-26.04
    permissions:
      contents: read
    steps:
      - name: Get the sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Validate Renovate configuration
        uses: suzuki-shunsuke/github-action-renovate-config-validator@b850926b611b1f3d3fe3729776339c217834bf2c # v2.2.0
        with:
          config_file_path: .github/renovate.json
