name: Unit tests

# Workflow Trigger
on:
  # Trigger the workflow on a pull request to any branch, ignoring changes to /docs
  pull_request:
    paths-ignore:
      - 'docs/**'
  # Trigger the workflow on pushes to the master branch, ignoring changes to /docs
  push:
    branches: 
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  Test:
    name: Run unit tests
    strategy:
      fail-fast: false
      matrix:
        os: [
          windows-2022, windows-2025, 
          ubuntu-22.04, ubuntu-24.04,
          # Cake.Recipe currently does not support macOS 14 (M1)
          macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - name: Install .NET
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
        with:
          # .NET 5 required for GitVersion
          dotnet-version: | 
            5.x
            8.x
            9.x
      # Ubuntu 24.04 does not have Mono installed, which is Required for Cake.Recipe
      - name: Install Mono
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        run: sudo apt-get install mono-complete
      - name: Test
        run: ./build.sh --target=Test
        shell: bash