name: Unit tests

# Workflow Trigger
on:
  # Trigger the workflow on a pull request to any branch
  pull_request:
  # Triggers the workflow in the event there is a push to master
  push:
    branches: 
      - master

jobs:
  Test:
    name: Run unit tests
    strategy:
      fail-fast: false
      matrix:
        os: [
          windows-2019, windows-2022,
          ubuntu-20.04, ubuntu-22.04, ubuntu-24.04,
          # Cake.Recipe currently does not support macOS 14 (M1)
          macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - name: Install .NET
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4
        with:
          # .NET 5 required for GitVersion
          dotnet-version: | 
            5.x
            6.x
            7.x
            8.x
      # Ubuntu 24.04 does not have Mono installed, which is Required for Cake.Recipe
      - name: Install Mono
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        run: sudo apt-get install mono-complete
      - name: Test
        run: ./build.sh --target=Test
        shell: bash