name: Unit tests

# Workflow Trigger
on:
  # Trigger the workflow on a pull request to any branch, ignoring changes to /docs
  pull_request:
    paths-ignore:
      - 'docs/**'
  # Trigger the workflow on pushes to the master branch, ignoring changes to /docs
  push:
    branches: 
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  Test:
    name: Run unit tests
    strategy:
      fail-fast: false
      matrix:
        os: [
          windows-2019, windows-2022,
          ubuntu-20.04, ubuntu-22.04, ubuntu-24.04,
          # Cake.Recipe currently does not support macOS 14 (M1)
          macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - name: Install .NET
        uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4
        with:
          # .NET 5 required for GitVersion
          dotnet-version: | 
            5.x
            8.x
            9.x
      # Ubuntu 24.04 does not have Mono installed, which is Required for Cake.Recipe
      - name: Install Mono
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        run: sudo apt-get install mono-complete
      - name: Test
        run: ./build.sh --target=Test
        shell: bash